---
title: "Class - Data Analysis with R"
author: "Chris"
date: "November 20, 2017"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(shiny)
data(diamonds)
```

## explore
```{r Explore Data}
summary(diamonds)
dim(diamonds)
nrow(diamonds)
ncol(diamonds)
str(diamonds)

```


# helper functions
```{r Helper Functions, echo = FALSE}
CountNumericColumns <- function(df){
  x = 0
  for (i in 1:ncol(df)){
    if (is.numeric(df[[i]]))
      x=x+1
  }
  return(x)
}
CountFactorColumns <- function(df){
  x = 0
  for (i in 1:ncol(df)){
    if (is.factor(df[[i]])) x = x + 1
  }
  return(x)
}

```

# using helper functions
```{r Run something, echo = FALSE}
CountNumericColumns(diamonds)
CountFactorColumns(diamonds)

str(diamonds)
diamonds$color %>% levels() %>% min()
```

```{r EDA, echo=FALSE}

Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
library(grid)


# shiny input
selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20)

renderPlot({

# still needs work on adjusting annotation labels
ggplot(diamonds, aes(price)) + geom_histogram(bins = as.numeric(input$n_breaks)) + 
  facet_wrap(~cut, scales = "free") +
  scale_x_continuous(trans = "log10") +
  geom_vline(xintercept = mean(diamonds$price), color = "aquamarine") +
  # annotate("text", x = mean(diamonds$price), y = 5555,
           # label = paste("Mean:",round(mean(diamonds$price))), vjust = 1, angle = 90) +
  geom_vline(xintercept = median(diamonds$price), color = "magenta")
  # annotate("text", x = median(diamonds$price), y = 5555,
           # label = paste("Median:", median(diamonds$price)), vjust = 1, angle = 90) +
  
  
  # mode is pretty useless on a histogram
  # geom_vline(xintercept = Mode(diamonds$price), color = "green")
  # annotate("text", x = Mode(diamonds$price), y = 2222,
           # label = paste("Mode:", Mode(diamonds$price)), vjust = 1, angle = 90)

  
  # annotation axis ticks. not working well
  # scale_x_continuous(formatter = "log10") 
  # scale_x_continuous(breaks = round(c(pretty(diamonds$price, 4), mean(diamonds$price))))
  # annotation_custom(textGrob("xyz", gp = gpar(col = "red")), 
  #                   xmin = 30, xmax = 555, ymin = .25, ymax = 5)
  # scale_x_continuous(breaks = c(0, 5000, 10000, 3000))

})

ggplot(diamonds, aes(x = "all diamonds", y = price)) + geom_boxplot()
ggplot(diamonds, aes(x = color, y = price)) + geom_boxplot()
  
```


```{r Explore One Variable}
library(dplyr)

# counts
diamonds$price[diamonds$price < 500] %>% length()
diamonds$price[diamonds$price < 250] %>% length()
diamonds$price[diamonds$price >= 15000] %>% length()

# mode
Mode(diamonds$price)

# max per group
diamonds %>% select(cut, price) %>% group_by(cut) %>% 
  summarise(maxprice = max(price), minprice = min(price), medianprice = median(price)) %>%
  arrange(desc(maxprice))

# summary stats of price by category
by(diamonds$price, diamonds$cut, summary)
by(diamonds[,"price"], diamonds[,"cut"], summary)
by(diamonds$price, diamonds$color, summary)

# visual summaries - boxplot
ggplot(diamonds, aes(cut, price)) + geom_boxplot()

by(diamonds$price, diamonds$carat, summary)

ggplot(diamonds, aes(x = carat)) + geom_histogram()

# PARAMETERIZE THIS ##
ggplot(diamonds, aes(x = carat, y = price, color = color, size = depth)) + geom_point() + 
  geom_vline(xintercept = median(diamonds$carat), color = "red") +
  geom_hline(yintercept = median(diamonds$price), color = "green") +
  geom_hline(yintercept = mean(diamonds$price), color = "darkgreen") +
  annotate(geom = "text", x = max(diamonds$carat), y = median(diamonds$price), 
           label = paste0("Median price: ", median(diamonds$price)), vjust = -.5, hjust = 1)

ggplot(diamonds, aes(x = factor("price"), y = price)) + geom_boxplot()
summary(diamonds$price)
```